version: '3.7'
services:
  proxy:
    image: nginx:1.13
    volumes:
      - ./config/proxy:/etc/nginx/conf.d
    ports:
      - "443:443"
  mocklogin:
    image: lblod/mock-login-service:0.3.1
  loket:
    restart: "no"
    environment:
      EMBER_FEATURE_PUBLIC_SERVICES_ENABLED: "true"
      EMBER_FEATURE_EREDIENSTEN_MANDATENBEHEER_ENABLED: "true"
      EMBER_FEATURE_WORSHIP_MINISTER_MANAGEMENT_ENABLED: "true"
      EMBER_WORSHIP_DECISIONS_DATABASE_URL: "https://dev.databankerediensten.lokaalbestuur.lblod.info"
      EMBER_WORSHIP_ORGANISATIONS_DATABASE_URL: "https://dev.organisaties.lokaalbestuur.lblod.info"
  dashboard:
    restart: "no"
  vendor-management:
    restart: "no"
  identifier:
    ports:
      - "90:80"
    restart: "no"
  dispatcher:
    restart: "no"
  database:
    restart: "no"
  virtuoso:
    ports:
      - "8890:8890"
    restart: "no"
  deltanotifier:
    restart: "no"
  migrations:
    restart: "no"
  cache:
    restart: "no"
  resource:
    restart: "no"
  login:
    restart: "no"
  file:
    restart: "no"
  dbcleanup:
    restart: "no"
  deliver-email-service:
    restart: "no"
  report-generation:
    restart: "no"
  enrich-submission:
    restart: "no"
  validate-submission:
    restart: "no"
  clean-up-submission:
    restart: "no"
  person-uri-for-social-security-number:
    restart: "no"
  sync-with-kalliope-error-notification:
    restart: "no"
  subsidy-applications-management:
    environment:
      VERSIONED_CONFIGURATION_WATCHER: null
    restart: "no"
  case-number-generator:
    restart: "no"
  subsidy-application-flow-management:
    restart: "no"
  publication-triplestore:
    restart: "no"
    ports:
      - "8891:8890"
  delta-producer-report-generator:
    restart: "no"
  delta-producer-dump-file-publisher:
    restart: "no"
  delta-producer-publication-graph-maintainer-ws-sensitive:
    restart: "no"
  error-alert:
    environment:
      EMAIL_FROM: "Loket Local <loket-development@redpencil.io>"
      EMAIL_TO: "loket-development@redpencil.io"
    restart: "no"
  update-bestuurseenheid-mock-login:
    restart: "no"
  reasoner:
    restart: "no"
  op-public-consumer:
    restart: "no"
  sparql-authorization-wrapper:
    restart: "no"
