version: '3.7'

services:
  frontend:
    restart: "no"
  identifier:
    restart: "no"
  dispatcher:
    restart: "no"
  mocklogin:
    image: lblod/mock-login-service:0.5.0
    restart: "no"
  deltanotifier:
    restart: "no"
  database:
    restart: "no"
  virtuoso:
    restart: "no"
    ports:
      - "8890:8890"
  migrations:
    restart: "no"
  cache:
    restart: "no"
  resource:
    restart: "no"
  login:
    restart: "no"
  file:
    restart: "no"
  deliver-email-service:
    restart: "no"
  report-generation:
    restart: "no"
  subsidy-applications-management:
    restart: "no"
  case-number-generator:
    restart: "no"
  jobs-controller:
    restart: "no"
  publication-triplestore:
    restart: "no"
    ports:
      - "8891:8890"
  delta-producer-report-generator:
    restart: "no"
  delta-producer-dump-file-publisher:
    restart: "no"
  delta-files-share:
    restart: "no"
  delta-producer-background-jobs-initiator-subsidies:
    restart: "no"
  delta-producer-publication-graph-maintainer-subsidies:
    restart: "no"
  subsidies-consumer:
    restart: "no"